# Generated by Django 3.2.15 on 2022-09-27 16:33

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='Hakkında')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website Linki')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook Linki')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram Linki')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='Youtube Linki')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Linkedin Linki')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter Linki')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_authors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yazar',
                'verbose_name_plural': 'Yazarlar',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Kategori')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Başlık')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Fotoğraf (800x460)')),
                ('content', ckeditor.fields.RichTextField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='blog.author', verbose_name='Yazarı')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='blog.category', verbose_name='Kategorisi')),
            ],
            options={
                'verbose_name_plural': 'Postlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
