# Generated by Django 3.2.15 on 2022-09-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220928_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='profiles/'),
        ),
    ]
