# Generated by Django 3.2.15 on 2022-09-29 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_newslettersubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersubscription',
            options={'verbose_name': 'Bülten Abonesi', 'verbose_name_plural': 'Bülten Aboneleri'},
        ),
        migrations.CreateModel(
            name='HitCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
    ]
