# Generated by Django 3.2.15 on 2022-10-02 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_auto_20220929_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hitcount',
            options={'verbose_name': 'Görüntülenme Sayısı', 'verbose_name_plural': 'Görüntülenme Sayıları'},
        ),
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog_authors', to=settings.AUTH_USER_MODEL),
        ),
    ]
