# Generated by Django 3.2.15 on 2022-10-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_author_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profiles/avatar.png', null=True, upload_to='profiles/'),
        ),
    ]
